# Workflow to test Files API on the CI server
name: Remote Testbed - PlayerIDAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      host:
        type: string
        description: "Which host to run test on"
        required: false
        default: ""
  push:
    branches:
      - "**"
    paths:
    - '.github/workflows/TEST_PlayerIDAPI_remote.yml'
    - '.github/actions/test_config/**'
    - 'tests/cases/apis/resources/**'
    - 'tests/config/**'
    - 'tests/PlayerIDAPITestConfig.py'
    - '!.github/workflows/CI_PlayerAPI.yml'
    - '!.github/actions/**'
    - '!src/**'
    - '!requirements.txt'

env:
  DEPLOY_URL:     ${{ inputs.host || vars.OGD_STAGING_HOST }}/${{ vars.API_BASE_URL }}/players/${{ github.ref_name }}/app.wsgi
  LOCAL_TEST_DIR: ./tests/cases/apis/PlayerIDAPISuite/**/RemoteCase.py
  PYTHONPATH: "src"

jobs:
  check_deploy:
    name: Check for Existing Deploy
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-player
      cancel-in-progress: false
    
    steps:
    - name: cURL Check Hello Endpoint
      run: curl -Is --fail-with-body https://${{ env.DEPLOY_URL }}/hello

  deploy_if_needed:
    name: PlayerIDAPI Deploy (If Needed)
    needs: check_deploy
    if: failure()
    uses: ./.github/workflows/DEPLOY_PlayerAPI.yml
    secrets: inherit
    with:
      deploy_host: ${{ vars.OGD_STAGING_HOST }}
      branch: ${{ github.ref_name }}
      remove: false

  run_testbed_files:
    name: Run PlayerIDAPI Testbed
    needs: [check_deploy, deploy_if_needed]
    if: always() && (needs.check_deploy.result == 'success' || needs.deploy_if_needed.result == 'success')
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-player
      cancel-in-progress: false

    steps:

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get Dependencies
      uses: opengamedata/actions-setup-ogd-py-dependencies@v1.0
      with:
        python_version: ${{ vars.OGD_PYTHON_VERSION }}
    - name: Get current version tag
      id: version-tag
      run: |
        echo "VERSION_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        echo "SRC_REVISION=$(git rev-list -1 HEAD -- src/)" >> $GITHUB_OUTPUT
    - name: Set up Config File
      uses: ./.github/actions/test_config
      with:
          endpoint: ${{ env.DEPLOY_URL }}
          api_version: ${{ steps.version-tag.outputs.VERSION_TAG }}-${{ github.ref_name }}-${{ steps.version-tag.outputs.SRC_REVISION }}
          verbose_output: "True"

  # 2. Build & configure remote environments

  # 3. Perform export
    - name: Execute testbed
      run: python -m unittest ${{ env.LOCAL_TEST_DIR }} 

  # 4. Cleanup & complete
    - name: Announce test completed
      run: echo "Tested PlayerIDAPI endpoint at ${{ env.DEPLOY_URL }}"
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./*.log
