# Workflow to test Files API on the CI server
name: Local Testbed - PlayerIDAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"
    paths:
    - '.github/workflows/TEST_PlayerIDAPI_local.yml'
    - '.github/actions/test_config/**'
    - 'tests/cases/apis/resources/**'
    - 'tests/config/**'
    - 'tests/PlayerIDAPITestConfig.py'
    - '!.github/workflows/CI_PlayerIDAPI.yml'
    - '!.github/actions/**'
    - '!src/**'
    - '!requirements.txt'

env:
  DEPLOY_URL:     ${{ vars.OGD_STAGING_HOST }}/${{ vars.API_BASE_URL }}/files/${{ github.ref_name }}/app.wsgi
  LOCAL_TEST_DIR: ./tests/cases/apis/resources/**/LocalCase.py
  PYTHONPATH: "src"

jobs:
  run_testbed_files:
    name: Run PlayerIDAPI Testbed
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-playerid
      cancel-in-progress: false

    steps:

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get Dependencies
      uses: opengamedata/actions-setup-ogd-py-dependencies@v1.0
      with:
        python_version: ${{ vars.OGD_PYTHON_VERSION }}
    - name: Local package install
      run: python -m pip install ./
    - name: Get current version tag
      id: version-tag
      run: |
        echo "VERSION_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        echo "SRC_REVISION=$(git rev-list -1 HEAD -- src/)" >> $GITHUB_OUTPUT
    - name: Set up Config File
      uses: ./.github/actions/test_config
      with:
          endpoint: ${{ env.DEPLOY_URL }}
          api_version: ${{ steps.version-tag.outputs.VERSION_TAG }}-${{ github.ref_name }}-${{ steps.version-tag.outputs.SRC_REVISION }}
          verbose_output: "True"

  # 2. Build & configure remote environments

  # 3. Perform export
    - name: Execute testbed
      run: python -m unittest ${{ env.LOCAL_TEST_DIR }} 

  # 4. Cleanup & complete
    - name: Announce test completed
      run: echo "Tested PlayerIDAPI endpoint at ${{ env.DEPLOY_URL }}"
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./*.log
